# Generated by Django 4.1.2 on 2023-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Auto',
            },
        ),

        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('auto', models.CharField(max_length=100)),

            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
